[package]
name = "desktop-linux-atspi"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
atspi.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tool-desktop.workspace = true
uuid.workspace = true
