//! Trusted host context and system-prompt composition.
use super::ToolProfile;
use file_target::ConversationFileContext;
use host_core::HostEnvironment;
use std::sync::{Arc, Mutex};

pub(crate) fn host_os_label() -> &'static str {
    host_core::host_os_label()
}

pub(crate) fn log_host_environment(environment: &HostEnvironment, tool_profile: ToolProfile) {
    let path_for_log = |path: Option<&std::path::Path>| {
        path.map(|path| path.display().to_string())
            .unwrap_or_else(|| "not_available".to_string())
    };
    let desktop_source = if environment.user_dirs.desktop.is_some() {
        if environment.xdg_config_source.is_some() {
            "xdg_user_dirs"
        } else {
            "platform"
        }
    } else {
        "unavailable"
    };
    tracing::debug!(
        host_os = %environment.os,
        home = %path_for_log(environment.home.as_deref()),
        desktop = %path_for_log(environment.user_dirs.desktop.as_deref()),
        documents = %path_for_log(environment.user_dirs.documents.as_deref()),
        downloads = %path_for_log(environment.user_dirs.downloads.as_deref()),
        desktop_source = %desktop_source,
        xdg_config_source = %path_for_log(environment.xdg_config_source.as_deref()),
        tool_profile = ?tool_profile,
        "native host environment resolved"
    );
}

/// Trusted native context appended to the user/character prompt. This is
/// generated by the Rust host, so the model does not need to guess a username,
/// operating system, or path syntax from its training data.
pub fn host_environment_context(autonomous_full_access: bool) -> String {
    host_environment_context_for(&HostEnvironment::snapshot(), autonomous_full_access)
}

fn host_environment_context_for(
    environment: &HostEnvironment,
    autonomous_full_access: bool,
) -> String {
    host_environment_context_for_context(environment, autonomous_full_access, None)
}

fn host_environment_context_for_context(
    environment: &HostEnvironment,
    autonomous_full_access: bool,
    file_context: Option<&Arc<Mutex<ConversationFileContext>>>,
) -> String {
    let mode_text = if autonomous_full_access {
        "enabled; native Agent capability requests are automatically authorized"
    } else {
        "disabled; normal Utsuwa permission policy applies"
    };
    let local_now = chrono::Local::now();
    let current_local_date = local_now.format("%Y-%m-%d").to_string();
    let current_local_datetime = local_now.to_rfc3339_opts(chrono::SecondsFormat::Secs, true);

    let mut lines = vec![
        "<host_environment>".to_string(),
        format!("OS: {}", host_os_label()),
        format!("Architecture: {}", environment.architecture),
        format!(
            "Available semantic user directories: {}",
            environment
                .user_dirs
                .resolved()
                .map(|(directory, _)| directory.json_key())
                .collect::<Vec<_>>()
                .join(", ")
        ),
    ];
    if environment.user_dirs.desktop.is_none() {
        lines.push("desktop directory: not available".to_string());
    }
    lines.extend([
        format!("Current local date: {current_local_date}"),
        format!("Current local datetime: {current_local_datetime}"),
        format!("Path separator: {}", environment.path_separator),
        format!("Path style: {}", environment.path_style),
        "Filesystem tools prefer file_ref or semantic directory ids with relative paths; absolute host-native paths are a compatibility fallback only. The exact native roots are host-owned and need not be reconstructed by the model.".to_string(),
        "Do not invent Windows drive-letter paths on a non-Windows host.".to_string(),
        "</host_environment>".to_string(),
    ]);
    if let Some(context) = file_context
        .and_then(|context| context.lock().ok())
        .and_then(|context| context.active_file.clone())
    {
        let display_name = context
            .as_str()
            .rsplit(['/', '\\'])
            .next()
            .filter(|name| !name.is_empty())
            .unwrap_or("unknown");
        lines.extend([
            "<active_file>".to_string(),
            format!("file_ref: {context}"),
            format!("display_name: {display_name}"),
            "Reuse this file_ref for follow-up filesystem operations about the same file."
                .to_string(),
            "</active_file>".to_string(),
        ]);
    }
    let runtime_lines = vec![
        "You are running inside the native Utsuwa desktop host.".to_string(),
        "Use the provided native tools when doing so is useful for completing the user's request."
            .to_string(),
        "Filesystem tools prefer file_ref from a previous successful operation, or target.directory plus target.relative_path. Directory values are semantic ids such as desktop and documents; never put a complete file path in a directory field."
            .to_string(),
        "Special filesystem directories are resolved by the operating system.".to_string(),
        "The host owns path resolution, localization, canonicalization, and capability validation. Do not reconstruct localized filesystem roots from display_path."
            .to_string(),
        "For creating new files in Desktop/Documents/etc., prefer filesystem.create_user_file with location and filename; do not first try filesystem.write or construct a special-directory path yourself. For existing files, use filesystem.edit."
            .to_string(),
        "You can create, read, overwrite, and edit files using the native filesystem tools."
            .to_string(),
        "To edit an existing file, use filesystem.edit: pass location and filename for a file in Desktop/Documents/etc., or path for an explicit absolute path; a unique existing filename may be resolved to its configured user directory when location is omitted. Never combine target styles unless both values identify the same file. The host preserves valid target, old_text, and new_text values across same-turn retries. For a UTF-8 file with exactly one non-empty line, the host can infer old_text when new_text is present; for multi-line files, call filesystem.read and use the exact old_text. For basic date/time replacements, new_text_source may be current_date, current_time, or current_datetime. Use system.time when exact fresh clock or timezone details are needed. Never use a placeholder such as 'Updated date'. Use filesystem.replace_user_file for a complete replacement."
            .to_string(),
        "For whole-file replacement in Desktop/Documents/etc. use filesystem.replace_user_file; to add text at the end use filesystem.append_user_file, or filesystem.append_file for an explicit absolute path."
            .to_string(),
        "If an edit operation fails because a path or text match was wrong, correct the tool arguments and retry. A failed edit attempt does not mean editing is unsupported. Do not offer to create a replacement file unless the user actually asks for a new file."
            .to_string(),
        "Do not tell the user that file editing is unavailable unless the native tool actually returns an unavailable or denied result."
            .to_string(),
        "For desktop capability questions use desktop.status; to see open windows use desktop.inspect. Filesystem Desktop and the graphical desktop backend are different."
            .to_string(),
        "Never translate filesystem directory names according to the language of the conversation."
            .to_string(),
        "\"Desktop\", \"escritorio\", \"bureau\", and similar words refer to the Desktop directory reported by the host; they do not mean a literal directory with that translated name."
            .to_string(),
        "Never guess /Desktop, /Escritorio, /Documents, C:\\Users, or another special directory."
            .to_string(),
        "If the host does not know a directory, inspect the filesystem with filesystem.list, filesystem.stat, or filesystem.glob before performing a mutation."
            .to_string(),
        "Never invent a path when its location is unknown.".to_string(),
        "If a tool returns an error, use its error information to correct the call rather than pretending the operation succeeded."
            .to_string(),
        format!(
            "Autonomous Full Access is {mode_text}. When it is enabled, you may use available native tools without asking the user for additional permission; the native host has already received the user's consent."
        ),
        "After a filesystem tool succeeds, use file_ref for later tool calls and display_path only for the human-facing final response."
            .to_string(),
        "Never claim an operation succeeded until the tool confirms success.".to_string(),
        "Never report success after a failed tool call.".to_string(),
        "For the current date or current time, call system.time. Never infer the current date or time from model knowledge.".to_string(),
    ];
    format!(
        "{}\n\n<utsuwa_native_runtime>\n{}\n</utsuwa_native_runtime>",
        lines.join("\n"),
        runtime_lines.join("\n")
    )
}

#[cfg(test)]
pub(crate) fn compose_host_system_prompt(
    user_prompt: Option<&str>,
    autonomous_full_access: bool,
) -> String {
    compose_host_system_prompt_for(
        user_prompt,
        autonomous_full_access,
        &HostEnvironment::snapshot(),
    )
}

#[cfg(test)]
pub(crate) fn compose_host_system_prompt_for(
    user_prompt: Option<&str>,
    autonomous_full_access: bool,
    environment: &HostEnvironment,
) -> String {
    compose_host_system_prompt_for_context(user_prompt, autonomous_full_access, environment, None)
}

pub(crate) fn compose_host_system_prompt_for_context(
    user_prompt: Option<&str>,
    autonomous_full_access: bool,
    environment: &HostEnvironment,
    file_context: Option<&Arc<Mutex<ConversationFileContext>>>,
) -> String {
    let host_context =
        host_environment_context_for_context(environment, autonomous_full_access, file_context);
    // A suspended native turn already contains the previous host context in
    // its system message. Rebuild from the original prompt portion so a mode
    // toggle updates the status without duplicating trusted runtime blocks.
    let user_prompt = user_prompt
        .map(|prompt| {
            prompt
                .split_once("\n\n<host_environment>")
                .map_or(prompt, |(base, _)| base)
        })
        .filter(|prompt| !prompt.is_empty());
    match user_prompt {
        Some(prompt) => format!("{prompt}\n\n{host_context}"),
        None => host_context,
    }
}
